version: '3.7'
services:
  jenkins:
    container_name: jenkins
    image: sekar/jenkins:0.0.1
    ports:
      - "8080:8080"
    networks:
      - overlay

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "9000:80"
    networks:
      - overlay

networks:
  overlay:
